blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/lantianhaijiao/pag-preview/discussions
    about: Suggest new features for consideration
  - name: Questions & Discussions
    url: https://github.com/lantianhaijiao/pag-preview/discussions
    about: Use GitHub discussions for message-board style questions and discussions.